package com.bank.bian.financialinstrumentvaluation;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Financial Instrument Valuation
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Markets and Treasury
 * Functional Pattern: Analyze
 * Asset Type:         Instrument Valuation
 * Control Record:     Instrument Valuation Analysis
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Financial Instrument Valuation — BIAN Semantic API")
                .description("Service Domain 'Financial Instrument Valuation' (Analyze pattern) "
                        + "operating on the 'Instrument Valuation Analysis' control record.")
                .version("0.1.0"));
    }
}
